### ISSUE TITLE
Ajouter ce bout de code (c'est pour tracker les zones chaudes et froides du site)

### ISSUE THREAD

**Issue by resandco-antigaspi** [louisremi/resandco-react#22]
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2015143,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by louisremi** [comment]
Il y a d'autres choses à faire pour avoir des informations utiles sur l'utilsation du site par ses visiteurs avant d'alourgir les pages avec un script supplémentaire pour la heatmap. Je ferme cette issue, on pourra réouvrir quand le besoin sera mieux défini.
