### ISSUE TITLE
Redirection http://www.res-and-co.fr et http://res-and-co.fr

### ISSUE THREAD

**Issue by resandco-antigaspi** [louisremi/resandco-react#23]
http://www.res-and-co.fr and http://res-and-co.fr should resolve to the same URL, but currently do not.

In order to pass this test you must consider using a 301 re-write rule in your .htaccess file so that both addresses (http://example.com and http://www.example.com) resolve to the same URL.

- If you want to redirect http://www.example.com to http://example.com, you can use this:

RewriteCond %{HTTP_HOST} ^www\.example\.com$
RewriteRule ^/?$ "http\:\/\/example\.com\/" [R=301,L]
- If you want to redirect http://example.com to http://www.example.com, you can use this:

RewriteCond %{HTTP_HOST} !^www.example.com$ [NC]
RewriteRule ^(.*)$ http://www.example.com/$1 [L,R=301]

**Comment by louisremi** [comment]
J'ai fait l'inverse, j'ai redirigé res-and-co.fr vers www.res-and-co.fr
Temps passé : 0.25h
