### ISSUE TITLE
Mettre le Https

### ISSUE THREAD

**Issue by resandco-antigaspi** [louisremi/resandco-react#24]
If your website needs a secured authentication or an encrypted transfer of data, you need to install an SSL certificate in order to provide a secure connection over HTTPS protocol. HERE is a "step by step" guide to purchase and install an SSL certificate.

https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

**Comment by louisremi** [comment]
Le site fonctionne déjà en https
