### ISSUE TITLE
Acceptation des CGV

### ISSUE THREAD

**Issue by resandco-antigaspi** [louisremi/resandco-react#5]
Où ? 
Réservez un restaurant > module de réservation 

Actuellement : lorsque l’on ne coche pas les CGV, rien ne se passe

Ce qu’il faut : lorsque l’on ne coche pas les CGV, mettre un message « Veuillez cocher les CGV » ou mettre une * pour indiquer la mention obligatoire

**Comment by louisremi** [comment]
Je prends l'option *, c'est relou de faire des messages d'erreur
