### ISSUE TITLE
Formulaire Tripetto

### ISSUE THREAD

**Issue by resandco-antigaspi** [louisremi/resandco-react#6]
« Votre réservation chez… est presque terminée… »
—> est-ce qu’il est censé y avoir marqué le nom du restaurant après « Chez » ? 

Actuellement : pas de nom de restaurant après « chez »

Est-il possible de configurer le formulaire en français ?
Est-ce qu’un mail de confirmation est envoyé une fois le formulaire rempli ?

**Comment by louisremi** [comment]
C'est résolu du côté Tripetto. J'ai passé tous les champs cahcés tout au début du formulaire sinon on ne pouvait pas les utilser
